[package]
name = "gseriwfuxv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
rust_decimal = "1.23"

[[bin]]
name = "gseriwfuxv"
path = "src/main.rs"
